"use strict";

import { CONFIG } from "./config.js";

/*
============================================================
 ASEM DIGITAL SOLUTIONS
 GLOBAL PLATFORM FRONTEND CONTROLLER
 FINAL APP.JS
============================================================

 This file controls the existing index.html.

 Real services are used only when their real endpoint/config
 exists. No fake payment transaction, fake GPS or fake API
 response is generated by this controller.
============================================================
*/

console.log("ASEM: app.js STARTED");

const ROOT = document.documentElement;

const CONFIG_SAFE =
    (CONFIG && typeof CONFIG === "object")
        ? CONFIG
        : {};

const API_CONFIG =
    CONFIG_SAFE.api &&
    typeof CONFIG_SAFE.api === "object"
        ? CONFIG_SAFE.api
        : {};

const API_BASE =
    API_CONFIG.real ||
    API_CONFIG.base ||
    "";

const TIMEOUT =
    Number(CONFIG_SAFE.timeout) > 0
        ? Number(CONFIG_SAFE.timeout)
        : 15000;

const ASEM = {

    version: "2026.08.final",

    selectors: {

        search:
            "#searchBox",

        language:
            "#langSwitch",

        theme:
            "#themeToggle",

        scrollTop:
            "#scrollTop",

        tourismGrid:
            "#tourismGrid",

        businessesGrid:
            "#businessesGrid",

        productsGrid:
            "#productsGrid",

        projectsGrid:
            "#projectsGrid",

        portfolioGrid:
            "#portfolioGrid"

    },

    sections: {

        tourism:
            "tourism-section",

        businesses:
            "businesses-section",

        products:
            "products-section",

        projects:
            "projects",

        portfolio:
            "portfolio",

        services:
            "services",

        contact:
            "contact",

        about:
            "about"

    },

    api: {

        tourism:
            API_CONFIG.tourism ||
            (API_BASE
                ? `${API_BASE}/tourism`
                : ""),

        businesses:
            API_CONFIG.businesses ||
            (API_BASE
                ? `${API_BASE}/businesses`
                : ""),

        products:
            API_CONFIG.products ||
            (API_BASE
                ? `${API_BASE}/products`
                : ""),

        projects:
            API_CONFIG.projects ||
            (API_BASE
                ? `${API_BASE}/projects`
                : ""),

        search:
            API_CONFIG.search ||
            (API_BASE
                ? `${API_BASE}/search`
                : ""),

        contact:
            API_CONFIG.contact ||
            (API_BASE
                ? `${API_BASE}/contact`
                : ""),

        location:
            API_CONFIG.location ||
            API_CONFIG.gps ||
            (API_BASE
                ? `${API_BASE}/location`
                : "")

    },

    storage: {

        theme:
            "asem-theme",

        language:
            "asem-language",

        location:
            "asem-location"

    },

    state: {

        initialized:
            false,

        language:
            "en",

        search:
            "",

        location:
            null,

        datasets: {

            tourism: [],

            businesses: [],

            products: [],

            projects: []

        },

        globalSearchOpen:
            false

    }

};


/* ========================================================
   DOM
======================================================== */

function $(selector, root = document) {

    if (!selector) {
        return null;
    }

    try {
        return root.querySelector(selector);
    } catch {
        return null;
    }

}


function $$(selector, root = document) {

    if (!selector) {
        return [];
    }

    try {
        return Array.from(
            root.querySelectorAll(selector)
        );
    } catch {
        return [];
    }

}


function byId(id) {

    if (!id) {
        return null;
    }

    return document.getElementById(id);

}


/* ========================================================
   SECURITY / TEXT
======================================================== */

function escapeHTML(value) {

    if (
        value === null ||
        value === undefined
    ) {
        return "";
    }

    return String(value)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;");

}


function safeURL(value) {

    if (!value) {
        return "";
    }

    try {

        const url =
            new URL(
                String(value),
                window.location.href
            );

        const allowed =
            [
                "http:",
                "https:",
                "mailto:",
                "tel:"
            ];

        if (
            !allowed.includes(
                url.protocol
            )
        ) {
            return "";
        }

        return url.href;

    } catch {

        return "";

    }

}


function text(value, fallback = "") {

    if (
        value === null ||
        value === undefined ||
        value === ""
    ) {
        return fallback;
    }

    return String(value);

}


/* ========================================================
   ARRAY NORMALIZATION
======================================================== */

function normalizeArray(data) {

    if (Array.isArray(data)) {
        return data;
    }

    if (
        !data ||
        typeof data !== "object"
    ) {
        return [];
    }

    const keys = [

        "data",
        "items",
        "results",
        "records",
        "tourism",
        "businesses",
        "products",
        "projects",
        "destinations",
        "services"

    ];

    for (
        const key of keys
    ) {

        if (
            Array.isArray(
                data[key]
            )
        ) {
            return data[key];
        }

    }

    return [];

}


/* ========================================================
   TRANSLATIONS
======================================================== */

const TRANSLATIONS = {

    en: {

        "ASEM Digital Solutions":
            "ASEM Digital Solutions",

        "Global Platform":
            "Global Platform",

        "Services":
            "Services",

        "Projects":
            "Projects",

        "Portfolio":
            "Portfolio",

        "About":
            "About",

        "Contact":
            "Contact",

        "Search...":
            "Search...",

        "Auto":
            "Auto",

        "Tourism":
            "Tourism",

        "Global Businesses":
            "Global Businesses",

        "Global Products":
            "Global Products",

        "Global Search":
            "Global Search",

        "Our Services":
            "Our Services",

        "Why Choose ASEM":
            "Why Choose ASEM",

        "Trusted Worldwide":
            "Trusted Worldwide",

        "Supported Payment Methods":
            "Supported Payment Methods",

        "Copy":
            "Copy",

        "Copied ✓":
            "Copied ✓",

        "Enterprise-grade security":
            "Enterprise-grade security",

        "Modern technologies":
            "Modern technologies",

        "Complete digital solutions":
            "Complete digital solutions",

        "Global digital platform":
            "Global digital platform"

    },

    ar: {

        "ASEM Digital Solutions":
            "ASEM للحلول الرقمية",

        "Global Platform":
            "المنصة العالمية",

        "Services":
            "الخدمات",

        "Projects":
            "المشروعات",

        "Portfolio":
            "سابقة الأعمال",

        "About":
            "من نحن",

        "Contact":
            "اتصل بنا",

        "Search...":
            "بحث...",

        "Auto":
            "تلقائي",

        "Tourism":
            "السياحة",

        "Global Businesses":
            "الأعمال العالمية",

        "Global Products":
            "المنتجات العالمية",

        "Global Search":
            "البحث العالمي",

        "Our Services":
            "خدماتنا",

        "Why Choose ASEM":
            "لماذا ASEM؟",

        "Trusted Worldwide":
            "موثوق عالميًا",

        "Supported Payment Methods":
            "وسائل الدفع المدعومة",

        "Copy":
            "نسخ",

        "Copied ✓":
            "تم النسخ ✓",

        "Enterprise-grade security":
            "أمان بمستوى المؤسسات",

        "Modern technologies":
            "تقنيات حديثة",

        "Complete digital solutions":
            "حلول رقمية متكاملة",

        "Global digital platform":
            "منصة رقمية عالمية"

    },

    fr: {

        "ASEM Digital Solutions":
            "ASEM Solutions Numériques",

        "Global Platform":
            "Plateforme mondiale",

        "Services":
            "Services",

        "Projects":
            "Projets",

        "Portfolio":
            "Portfolio",

        "About":
            "À propos",

        "Contact":
            "Contact",

        "Search...":
            "Rechercher...",

        "Auto":
            "Automatique",

        "Tourism":
            "Tourisme",

        "Global Businesses":
            "Entreprises mondiales",

        "Global Products":
            "Produits mondiaux",

        "Global Search":
            "Recherche mondiale",

        "Our Services":
            "Nos services",

        "Why Choose ASEM":
            "Pourquoi choisir ASEM ?",

        "Trusted Worldwide":
            "Reconnu dans le monde",

        "Supported Payment Methods":
            "Modes de paiement acceptés",

        "Copy":
            "Copier",

        "Copied ✓":
            "Copié ✓",

        "Enterprise-grade security":
            "Sécurité de niveau entreprise",

        "Modern technologies":
            "Technologies modernes",

        "Complete digital solutions":
            "Solutions numériques complètes",

        "Global digital platform":
            "Plateforme numérique mondiale"

    },

    ja: {

        "ASEM Digital Solutions":
            "ASEMデジタルソリューションズ",

        "Global Platform":
            "グローバルプラットフォーム",

        "Services":
            "サービス",

        "Projects":
            "プロジェクト",

        "Portfolio":
            "ポートフォリオ",

        "About":
            "会社情報",

        "Contact":
            "お問い合わせ",

        "Search...":
            "検索...",

        "Auto":
            "自動",

        "Tourism":
            "観光",

        "Global Businesses":
            "グローバルビジネス",

        "Global Products":
            "グローバル製品",

        "Global Search":
            "グローバル検索",

        "Our Services":
            "サービス一覧",

        "Why Choose ASEM":
            "ASEMを選ぶ理由",

        "Trusted Worldwide":
            "世界で信頼される",

        "Supported Payment Methods":
            "対応決済方法",

        "Copy":
            "コピー",

        "Copied ✓":
            "コピーしました ✓",

        "Enterprise-grade security":
            "エンタープライズ級セキュリティ",

        "Modern technologies":
            "最新テクノロジー",

        "Complete digital solutions":
            "総合デジタルソリューション",

        "Global digital platform":
            "グローバルデジタルプラットフォーム"

    }

};


/* ========================================================
   LANGUAGE
======================================================== */

function detectLanguage() {

    const language =
        String(
            navigator.language ||
            "en"
        ).toLowerCase();

    if (
        language.startsWith("ar")
    ) {
        return "ar";
    }

    if (
        language.startsWith("fr")
    ) {
        return "fr";
    }

    if (
        language.startsWith("ja")
    ) {
        return "ja";
    }

    return "en";

}


function translateText(value) {

    const language =
        ASEM.state.language;

    const dictionary =
        TRANSLATIONS[language] ||
        TRANSLATIONS.en;

    return dictionary[value] ||
        value;

}


function translateDocument() {

    const dictionary =
        TRANSLATIONS[
            ASEM.state.language
        ] || TRANSLATIONS.en;

    const walker =
        document.createTreeWalker(
            document.body,
            NodeFilter.SHOW_TEXT
        );

    const nodes = [];

    let node;

    while (
        (node = walker.nextNode())
    ) {

        nodes.push(node);

    }

    nodes.forEach(node => {

        const original =
            node.nodeValue.trim();

        if (!original) {
            return;
        }

        if (
            dictionary[
                original
            ]
        ) {

            node.nodeValue =
                node.nodeValue.replace(
                    original,
                    dictionary[original]
                );

        }

    });

    $$(
        "input[placeholder]"
    ).forEach(input => {

        const original =
            input.getAttribute(
                "placeholder"
            );

        if (
            dictionary[
                original
            ]
        ) {

            input.setAttribute(
                "placeholder",
                dictionary[original]
            );

        }

    });

}


function applyLanguage(language) {

    const selected =
        language === "auto"
            ? detectLanguage()
            : (
                [
                    "ar",
                    "en",
                    "fr",
                    "ja"
                ].includes(language)
                    ? language
                    : "en"
            );

    ASEM.state.language =
        selected;

    ROOT.setAttribute(
        "lang",
        selected
    );

    ROOT.setAttribute(
        "dir",
        selected === "ar"
            ? "rtl"
            : "ltr"
    );

    try {

        localStorage.setItem(
            ASEM.storage.language,
            language || selected
        );

    } catch {}

    const selector =
        $(ASEM.selectors.language);

    if (selector) {

        const exists =
            Array.from(
                selector.options
            ).some(
                option =>
                    option.value === language
            );

        if (exists) {
            selector.value =
                language;
        }

    }

    translateDocument();

    document.dispatchEvent(
        new CustomEvent(
            "asem:languagechange",
            {
                detail: {
                    language: selected
                }
            }
        )
    );

    return selected;

}


function initializeLanguage() {

    let saved =
        "auto";

    try {

        saved =
            localStorage.getItem(
                ASEM.storage.language
            ) || "auto";

    } catch {}

    const selector =
        $(ASEM.selectors.language);

    if (selector) {

        const exists =
            Array.from(
                selector.options
            ).some(
                option =>
                    option.value === saved
            );

        if (exists) {

            selector.value =
                saved;

        }

    }

    applyLanguage(
        selector?.value ||
        saved
    );

}


function initializeLanguageEvents() {

    const selector =
        $(ASEM.selectors.language);

    if (!selector) {
        return;
    }

    selector.addEventListener(
        "change",
        event => {

            applyLanguage(
                event.target.value
            );

        }
    );

}


/* ========================================================
   THEME
======================================================== */

function applyTheme(theme) {

    const valid =
        theme === "dark"
            ? "dark"
            : "light";

    ROOT.setAttribute(
        "data-theme",
        valid
    );

    const button =
        $(ASEM.selectors.theme);

    if (button) {

        button.textContent =
            valid === "dark"
                ? "☀️"
                : "🌙";

        button.setAttribute(
            "aria-label",
            valid === "dark"
                ? "Switch to light mode"
                : "Switch to dark mode"
        );

    }

    try {

        localStorage.setItem(
            ASEM.storage.theme,
            valid
        );

    } catch {}

    return valid;

}


function initializeTheme() {

    let saved = null;

    try {

        saved =
            localStorage.getItem(
                ASEM.storage.theme
            );

    } catch {}

    if (
        saved === "dark" ||
        saved === "light"
    ) {

        applyTheme(saved);
        return;

    }

    const dark =
        window.matchMedia &&
        window.matchMedia(
            "(prefers-color-scheme: dark)"
        ).matches;

    applyTheme(
        dark
            ? "dark"
            : "light"
    );

}


function toggleTheme() {

    const current =
        ROOT.getAttribute(
            "data-theme"
        );

    applyTheme(
        current === "dark"
            ? "light"
            : "dark"
    );

}


function initializeThemeEvents() {

    const button =
        $(ASEM.selectors.theme);

    if (!button) {
        return;
    }

    button.addEventListener(
        "click",
        toggleTheme
    );

}


/* ========================================================
   API
======================================================== */

async function apiRequest(
    endpoint,
    options = {}
) {

    if (!endpoint) {

        throw new Error(
            "API endpoint is not configured"
        );

    }

    const controller =
        new AbortController();

    const timer =
        window.setTimeout(
            () =>
                controller.abort(),
            TIMEOUT
        );

    try {

        const response =
            await fetch(
                endpoint,
                {
                    method:
                        options.method ||
                        "GET",

                    headers: {

                        Accept:
                            "application/json",

                        ...(options.body
                            ? {
                                "Content-Type":
                                    "application/json"
                            }
                            : {}),

                        ...(options.headers || {})

                    },

                    body:
                        options.body
                            ? JSON.stringify(
                                options.body
                            )
                            : undefined,

                    cache:
                        "no-store",

                    credentials:
                        options.credentials ||
                        "same-origin",

                    signal:
                        controller.signal

                }
            );

        if (!response.ok) {

            throw new Error(
                `HTTP ${response.status}`
            );

        }

        const contentType =
            response.headers.get(
                "content-type"
            ) || "";

        if (
            !contentType.includes(
                "application/json"
            )
        ) {

            throw new Error(
                "API response is not JSON"
            );

        }

        return await response.json();

    } finally {

        window.clearTimeout(timer);

    }

}


/* ========================================================
   GRID STATES
======================================================== */

function setGridLoading(
    grid,
    message
) {

    if (!grid) {
        return;
    }

    grid.setAttribute(
        "aria-busy",
        "true"
    );

    grid.innerHTML = `

        <article
            class="card platform-state loading-state">

            <div
                class="loading-spinner"
                aria-hidden="true">
            </div>

            <h3>
                ${escapeHTML(
                    message ||
                    "Loading..."
                )}
            </h3>

            <p>
                ${escapeHTML(
                    ASEM.state.language === "ar"
                        ? "يرجى الانتظار..."
                        : "Please wait..."
                )}
            </p>

        </article>

    `;

}


function setGridEmpty(
    grid,
    title,
    message
) {

    if (!grid) {
        return;
    }

    grid.setAttribute(
        "aria-busy",
        "false"
    );

    grid.innerHTML = `

        <article
            class="card platform-state empty-state">

            <span
                class="platform-state-icon"
                aria-hidden="true">
                🌐
            </span>

            <h3>
                ${escapeHTML(title)}
            </h3>

            <p>
                ${escapeHTML(message)}
            </p>

        </article>

    `;

}


function setGridError(
    grid,
    title,
    message
) {

    if (!grid) {
        return;
    }

    grid.setAttribute(
        "aria-busy",
        "false"
    );

    grid.innerHTML = `

        <article
            class="card platform-state error-state">

            <span
                class="platform-state-icon"
                aria-hidden="true">
                ⚠️
            </span>

            <h3>
                ${escapeHTML(title)}
            </h3>

            <p>
                ${escapeHTML(message)}
            </p>

            <button
                type="button"
                class="btn"
                data-retry-grid="${escapeHTML(
                    grid.id
                )}">
                Retry
            </button>

        </article>

    `;

}


/* ========================================================
   CARD HELPERS
======================================================== */

function getImage(item) {

    return (
        item.image ||
        item.cover_image ||
        item.logo ||
        item.thumbnail ||
        ""
    );

}


function getName(item, fallback) {

    return (
        item.name ||
        item.title ||
        item.business_name ||
        item.product_name ||
        fallback
    );

}


function getDescription(
    item,
    fallback
) {

    return (
        item.description ||
        item.summary ||
        item.excerpt ||
        fallback
    );

}


function makeCopyData(
    parts
) {

    return parts
        .filter(
            value =>
                value !== null &&
                value !== undefined &&
                value !== ""
        )
        .join("\n");

}


function imageHTML(
    image,
    name,
    icon
) {

    const url =
        safeURL(image);

    if (!url) {

        return `

            <div
                class="platform-card-icon"
                aria-hidden="true">
                ${icon}
            </div>

        `;

    }

    return `

        <img
            src="${escapeHTML(url)}"
            alt="${escapeHTML(name)}"
            loading="lazy"
            class="platform-card-image"
            onerror="
                this.style.display='none';
                if(this.nextElementSibling)
                    this.nextElementSibling.style.display='flex';
            ">

        <div
            class="platform-card-icon"
            aria-hidden="true"
            style="display:none">
            ${icon}
        </div>

    `;

}


/* ========================================================
   TOURISM
======================================================== */

function buildTourismCard(item) {

    const id =
        item.id ||
        item.slug ||
        "";

    const name =
        getName(
            item,
            "Tourism Destination"
        );

    const category =
        item.category ||
        "Tourism";

    const description =
        getDescription(
            item,
            "Discover this destination."
        );

    const image =
        getImage(item);

    const copy =
        makeCopyData(
            [
                name,
                category,
                description,
                item.address
            ]
        );

    return `

        <article
            class="card platform-result-card"
            data-type="tourism"
            data-id="${escapeHTML(id)}"
            tabindex="0">

            ${imageHTML(
                image,
                name,
                "🏝️"
            )}

            <div
                class="platform-card-content">

                <span
                    class="platform-card-category">
                    ${escapeHTML(category)}
                </span>

                <h3>
                    ${escapeHTML(name)}
                </h3>

                <p>
                    ${escapeHTML(description)}
                </p>

                ${
                    item.rating !== undefined
                        ? `
                            <div
                                class="platform-rating">
                                ⭐ ${escapeHTML(
                                    item.rating
                                )}
                            </div>
                          `
                        : ""
                }

                ${
                    item.address
                        ? `
                            <small>
                                📍 ${escapeHTML(
                                    item.address
                                )}
                            </small>
                          `
                        : ""
                }

                <div
                    class="platform-card-actions">

                    <button
                        type="button"
                        class="btn copy-card-btn"
                        data-copy="${escapeHTML(copy)}">
                        ${translateText("Copy")}
                    </button>

                    ${
                        item.url ||
                        item.website ||
                        item.link
                            ? `
                                <button
                                    type="button"
                                    class="btn card-open-link"
                                    data-open-url="${escapeHTML(
                                        safeURL(
                                            item.url ||
                                            item.website ||
                                            item.link
                                        )
                                    )}">
                                    Open
                                </button>
                              `
                            : ""
                    }

                </div>

            </div>

        </article>

    `;

}


/* ========================================================
   BUSINESSES
======================================================== */

function buildBusinessCard(item) {

    const id =
        item.id ||
        item.slug ||
        "";

    const name =
        getName(
            item,
            "Global Business"
        );

    const category =
        item.category ||
        "Business";

    const description =
        getDescription(
            item,
            "Discover this business."
        );

    const image =
        getImage(item);

    const address =
        item.address ||
        item.location ||
        "";

    const copy =
        makeCopyData(
            [
                name,
                category,
                description,
                address
            ]
        );

    return `

        <article
            class="card platform-result-card"
            data-type="business"
            data-id="${escapeHTML(id)}"
            tabindex="0">

            ${imageHTML(
                image,
                name,
                "🌍"
            )}

            <div
                class="platform-card-content">

                <span
                    class="platform-card-category">
                    ${escapeHTML(category)}
                </span>

                <h3>
                    ${escapeHTML(name)}
                </h3>

                <p>
                    ${escapeHTML(description)}
                </p>

                ${
                    address
                        ? `
                            <small>
                                📍 ${escapeHTML(
                                    address
                                )}
                            </small>
                          `
                        : ""
                }

                ${
                    item.rating !== undefined
                        ? `
                            <div
                                class="platform-rating">
                                ⭐ ${escapeHTML(
                                    item.rating
                                )}
                            </div>
                          `
                        : ""
                }

                <div
                    class="platform-card-actions">

                    <button
                        type="button"
                        class="btn copy-card-btn"
                        data-copy="${escapeHTML(copy)}">
                        ${translateText("Copy")}
                    </button>

                    ${
                        item.website ||
                        item.url ||
                        item.link
                            ? `
                                <button
                                    type="button"
                                    class="btn card-open-link"
                                    data-open-url="${escapeHTML(
                                        safeURL(
                                            item.website ||
                                            item.url ||
                                            item.link
                                        )
                                    )}">
                                    Open
                                </button>
                              `
                            : ""
                    }

                </div>

            </div>

        </article>

    `;

}


/* ========================================================
   PRODUCTS
======================================================== */

function buildProductCard(item) {

    const id =
        item.id ||
        item.slug ||
        "";

    const name =
        getName(
            item,
            "Global Product"
        );

    const category =
        item.category ||
        "Product";

    const description =
        getDescription(
            item,
            "Discover this product."
        );

    const image =
        getImage(item);

    const price =
        item.price !== undefined
            ? `${item.price} ${item.currency || "USD"}`
            : "";

    const copy =
        makeCopyData(
            [
                name,
                category,
                description,
                price
            ]
        );

    return `

        <article
            class="card platform-result-card"
            data-type="product"
            data-id="${escapeHTML(id)}"
            tabindex="0">

            ${imageHTML(
                image,
                name,
                "🛒"
            )}

            <div
                class="platform-card-content">

                <span
                    class="platform-card-category">
                    ${escapeHTML(category)}
                </span>

                <h3>
                    ${escapeHTML(name)}
                </h3>

                <p>
                    ${escapeHTML(description)}
                </p>

                ${
                    price
                        ? `
                            <strong
                                class="product-price">
                                ${escapeHTML(price)}
                            </strong>
                          `
                        : ""
                }

                ${
                    item.rating !== undefined
                        ? `
                            <div
                                class="platform-rating">
                                ⭐ ${escapeHTML(
                                    item.rating
                                )}
                            </div>
                          `
                        : ""
                }

                <div
                    class="platform-card-actions">

                    <button
                        type="button"
                        class="btn copy-card-btn"
                        data-copy="${escapeHTML(copy)}">
                        ${translateText("Copy")}
                    </button>

                    ${
                        item.url ||
                        item.website ||
                        item.link ||
                        item.checkout
                            ? `
                                <button
                                    type="button"
                                    class="btn card-open-link"
                                    data-open-url="${escapeHTML(
                                        safeURL(
                                            item.checkout ||
                                            item.url ||
                                            item.website ||
                                            item.link
                                        )
                                    )}">
                                    Open
                                </button>
                              `
                            : ""
                    }

                </div>

            </div>

        </article>

    `;

}


/* ========================================================
   PROJECTS
======================================================== */

function buildProjectCard(item) {

    const id =
        item.id ||
        item.slug ||
        "";

    const name =
        getName(
            item,
            "ASEM Project"
        );

    const description =
        getDescription(
            item,
            "ASEM Digital Solutions project."
        );

    const image =
        getImage(item);

    const copy =
        makeCopyData(
            [
                name,
                description
            ]
        );

    return `

        <article
            class="card project-card"
            data-type="project"
            data-id="${escapeHTML(id)}"
            tabindex="0">

            ${imageHTML(
                image,
                name,
                "🚀"
            )}

            <h3>
                ${escapeHTML(name)}
            </h3>

            <p>
                ${escapeHTML(description)}
            </p>

            <div
                class="platform-card-actions">

                <button
                    type="button"
                    class="btn copy-card-btn"
                    data-copy="${escapeHTML(copy)}">
                    ${translateText("Copy")}
                </button>

                ${
                    item.url ||
                    item.website ||
                    item.link
                        ? `
                            <button
                                type="button"
                                class="btn card-open-link"
                                data-open-url="${escapeHTML(
                                    safeURL(
                                        item.url ||
                                        item.website ||
                                        item.link
                                    )
                                )}">
                                Open
                            </button>
                          `
                        : ""
                }

            </div>

        </article>

    `;

}


/* ========================================================
   RENDER
======================================================== */

function renderGrid(
    grid,
    items,
    builder,
    emptyTitle,
    emptyMessage
) {

    if (!grid) {
        return;
    }

    if (!Array.isArray(items)) {
        items = [];
    }

    if (!items.length) {

        setGridEmpty(
            grid,
            emptyTitle,
            emptyMessage
        );

        return;

    }

    grid.innerHTML =
        items
            .map(
                item => {

                    try {
                        return builder(item || {});
                    } catch (error) {

                        console.error(
                            "ASEM card render error",
                            error
                        );

                        return "";

                    }

                }
            )
            .filter(Boolean)
            .join("");

    grid.setAttribute(
        "aria-busy",
        "false"
    );

}


/* ========================================================
   LOADERS
======================================================== */

async function loadDataset(
    type,
    selector,
    builder,
    title,
    message
) {

    const grid =
        $(selector);

    if (!grid) {
        return [];
    }

    const endpoint =
        ASEM.api[type];

    if (!endpoint) {

        setGridEmpty(
            grid,
            title,
            message
        );

        return [];

    }

    setGridLoading(
        grid,
        `Loading ${title}...`
    );

    try {

        const data =
            await apiRequest(
                endpoint
            );

        const items =
            normalizeArray(data);

        ASEM.state.datasets[type] =
            items;

        renderGrid(
            grid,
            items,
            builder,
            title,
            message
        );

        return items;

    } catch (error) {

        console.error(
            `ASEM ${type}:`,
            error
        );

        setGridError(
            grid,
            `${title} unavailable`,
            "The real service could not be reached."
        );

        return [];

    }

}


async function loadTourism() {

    return loadDataset(
        "tourism",
        ASEM.selectors.tourismGrid,
        buildTourismCard,
        "Global Tourism",
        "Tourism destinations will appear here."
    );

}


async function loadBusinesses() {

    return loadDataset(
        "businesses",
        ASEM.selectors.businessesGrid,
        buildBusinessCard,
        "Global Businesses",
        "Businesses will appear here."
    );

}


async function loadProducts() {

    return loadDataset(
        "products",
        ASEM.selectors.productsGrid,
        buildProductCard,
        "Global Products",
        "Products will appear here."
    );

}


async function loadProjects() {

    return loadDataset(
        "projects",
        ASEM.selectors.projectsGrid,
        buildProjectCard,
        "ASEM Projects",
        "Our projects will appear here."
    );

}


/* ========================================================
   NAVIGATION
======================================================== */

function openPageSection(id) {

    const section =
        byId(id);

    if (!section) {

        console.warn(
            `ASEM: section #${id} not found`
        );

        return false;

    }

    section.hidden = false;

    section.removeAttribute(
        "aria-hidden"
    );

    section.scrollIntoView({
        behavior: "smooth",
        block: "start"
    });

    return true;

}


function openExternalPage(page) {

    const url =
        safeURL(page);

    if (!url) {
        return false;
    }

    window.location.assign(
        url
    );

    return true;

}


/* ========================================================
   PORTFOLIO
======================================================== */

function openPortfolio() {

    if (
        !openPageSection(
            ASEM.sections.portfolio
        )
    ) {
        return;
    }

    const grid =
        $(ASEM.selectors.portfolioGrid);

    if (!grid) {
        return;
    }

    if (
        grid.children.length === 0
    ) {

        grid.innerHTML = `

            <article
                class="card portfolio-card">

                <div
                    class="platform-card-icon"
                    aria-hidden="true">
                    💻
                </div>

                <h3>
                    ASEM Digital Solutions
                </h3>

                <p>
                    Global digital solutions,
                    software platforms and
                    modern technology services.
                </p>

                <button
                    type="button"
                    class="btn"
                    data-platform-action="contact">
                    ${translateText("Contact")}
                </button>

            </article>

        `;

    }

}


/* ========================================================
   SERVICES
======================================================== */

function openServices() {

    return openPageSection(
        ASEM.sections.services
    );

}


/* ========================================================
   ABOUT
======================================================== */

function openAbout() {

    const section =
        byId(
            ASEM.sections.about
        );

    if (section) {

        openPageSection(
            ASEM.sections.about
        );

        return;

    }

    openExternalPage(
        "about.html"
    );

}


/* ========================================================
   CONTACT
======================================================== */

function openContact() {

    const section =
        byId(
            ASEM.sections.contact
        );

    if (section) {

        openPageSection(
            ASEM.sections.contact
        );

        return;

    }

    openExternalPage(
        "contact.html"
    );

}


/* ========================================================
   SEARCH
======================================================== */

function focusSearch() {

    const input =
        $(ASEM.selectors.search);

    if (!input) {
        return;
    }

    input.focus();

    input.scrollIntoView({
        behavior: "smooth",
        block: "center"
    });

}


function localSearch(query) {

    const normalized =
        String(query || "")
            .toLowerCase()
            .trim();

    const cards =
        $(
            ".platform-result-card, .project-card"
        );

    cards.forEach(card => {

        if (!normalized) {

            card.hidden =
                false;

            return;

        }

        card.hidden =
            !card.textContent
                .toLowerCase()
                .includes(normalized);

    });

}


async function remoteSearch(query) {

    if (
        !query ||
        !ASEM.api.search
    ) {
        return [];
    }

    try {

        const separator =
            ASEM.api.search.includes("?")
                ? "&"
                : "?";

        const endpoint =
            `${ASEM.api.search}${separator}q=${encodeURIComponent(query)}`;

        const data =
            await apiRequest(
                endpoint
            );

        return normalizeArray(
            data
        );

    } catch (error) {

        console.warn(
            "ASEM Global Search API:",
            error
        );

        return [];

    }

}


async function search(value) {

    const query =
        String(value || "")
            .trim();

    ASEM.state.search =
        query;

    localSearch(query);

    if (!query) {
        return [];
    }

    const remote =
        await remoteSearch(
            query
        );

    return remote;

}


function openGlobalSearch() {

    const existing =
        byId(
            "asem-global-search"
        );

    if (existing) {

        existing.hidden =
            false;

        const input =
            existing.querySelector(
               ("input")
            );

        input?.focus();

        return;

    }

    const modal =
        document.createElement(
            "div"
        );

    modal.id =
        "asem-global-search";

    modal.className =
        "asem-global-search-overlay";

    modal.innerHTML = `

        <div
            class="asem-global-search-panel"
            role="dialog"
            aria-modal="true"
            aria-label="Global Search">

            <button
                type="button"
                class="asem-search-close"
                data-asem-close-search>
                ×
            </button>

            <h2>
                🔍 Global Search
            </h2>

            <input
                type="search"
                autocomplete="off"
                placeholder="Search the ASEM platform..."
                data-asem-global-search-input>

            <div
                class="asem-global-search-status"
                data-asem-global-search-status>
            </div>

            <div
                class="asem-global-search-results"
                data-asem-global-search-results>
            </div>

            <div
                class="asem-global-location-tools">

                <button
                    type="button"
                    class="btn"
                    data-asem-gps>
                    📍 Use my location
                </button>

                <span
                    data-asem-location-status>
                </span>

            </div>

        </div>

    `;

    document.body.appendChild(
        modal
    );

    ASEM.state.globalSearchOpen =
        true;

    const input =
        modal.querySelector(
            "[data-asem-global-search-input]"
        );

    const status =
        modal.querySelector(
            "[data-asem-global-search-status]"
        );

    const results =
        modal.querySelector(
            "[data-asem-global-search-results]"
        );

    let searchTimer = null;

    input?.addEventListener(
        "input",
        event => {

            clearTimeout(
                searchTimer
            );

            const query =
                event.target.value
                    .trim();

            localSearch(query);

            if (!query) {

                status.textContent =
                    "";

                results.innerHTML =
                    "";

                return;

            }

            status.textContent =
                "Searching...";

            searchTimer =
                setTimeout(
                    async () => {

                        const remote =
                            await remoteSearch(
                                query
                            );

                        renderGlobalSearchResults(
                            results,
                            remote,
                            query
                        );

                        status.textContent =
                            remote.length
                                ? `${remote.length} result(s)`
                                : "Showing local platform results.";

                    },
                    350
                );

        }
    );

    modal.addEventListener(
        "click",
        event => {

            if (
                event.target ===
                modal
            ) {

                closeGlobalSearch();

            }

        }
    );

    modal.querySelector(
        "[data-asem-close-search]"
    )?.addEventListener(
        "click",
        closeGlobalSearch
    );

    modal.querySelector(
        "[data-asem-gps]"
    )?.addEventListener(
        "click",
        requestGPS
    );

    input?.focus();

}


function renderGlobalSearchResults(
    container,
    items,
    query
) {

    if (!container) {
        return;
    }

    if (!items.length) {

        container.innerHTML = `

            <div
                class="asem-search-empty">

                No remote results for
                <strong>
                    ${escapeHTML(query)}
                </strong>.

                <br>

                Local platform results
                have already been filtered.

            </div>

        `;

        return;

    }

    container.innerHTML =
        items.map(
            item => {

                const name =
                    getName(
                        item,
                        "Search Result"
                    );

                const description =
                    getDescription(
                        item,
                        ""
                    );

                const url =
                    safeURL(
                        item.url ||
                        item.website ||
                        item.link
                    );

                return `

                    <article
                        class="card asem-search-result">

                        <h3>
                            ${escapeHTML(name)}
                        </h3>

                        <p>
                            ${escapeHTML(
                                description
                            )}
                        </p>

                        ${
                            url
                                ? `
                                    <button
                                        type="button"
                                        class="btn card-open-link"
                                        data-open-url="${escapeHTML(url)}">
                                        Open
                                    </button>
                                  `
                                : ""
                        }

                    </article>

                `;

            }
        ).join("");

}


function closeGlobalSearch() {

    const modal =
        byId(
            "asem-global-search"
        );

    if (modal) {

        modal.remove();

    }

    ASEM.state.globalSearchOpen =
        false;

}


/* ========================================================
   GPS / GEOLOCATION
======================================================== */

function requestGPS() {

    if (
        !("geolocation" in navigator)
    ) {

        showLocationStatus(
            "Geolocation is not supported by this browser."
        );

        return;

    }

    showLocationStatus(
        "Requesting your location..."
    );

    navigator.geolocation.getCurrentPosition(

        position => {

            const location = {

                latitude:
                    position.coords.latitude,

                longitude:
                    position.coords.longitude,

                accuracy:
                    position.coords.accuracy,

                timestamp:
                    Date.now()

            };

            ASEM.state.location =
                location;

            try {

                localStorage.setItem(
                    ASEM.storage.location,
                    JSON.stringify(
                        location
                    )
                );

            } catch {}

            showLocationStatus(
                `Location acquired (${location.latitude.toFixed(5)}, ${location.longitude.toFixed(5)})`
            );

            document.dispatchEvent(
                new CustomEvent(
                    "asem:locationchange",
                    {
                        detail:
                            location
                    }
                )
            );

            sendLocationToBackend(
                location
            );

        },

        error => {

            let message =
                "Unable to obtain location.";

            if (
                error.code ===
                error.PERMISSION_DENIED
            ) {

                message =
                    "Location permission was denied.";

            } else if (
                error.code ===
                error.POSITION_UNAVAILABLE
            ) {

                message =
                    "Location is currently unavailable.";

            } else if (
                error.code ===
                error.TIMEOUT
            ) {

                message =
                    "Location request timed out.";

            }

            console.warn(
                "ASEM GPS:",
                error
            );

            showLocationStatus(
                message
            );

        },

        {

            enableHighAccuracy:
                true,

            timeout:
                15000,

            maximumAge:
                0

        }

    );

}


function showLocationStatus(
    message
) {

    const elements =
        $$(
            "[data-asem-location-status]"
        );

    elements.forEach(
        element => {

            element.textContent =
                message || "";

        }
    );

}


async function sendLocationToBackend(
    location
) {

    if (
        !ASEM.api.location
    ) {
        return;
    }

    try {

        await apiRequest(
            ASEM.api.location,
            {

                method:
                    "POST",

                body:
                    location

            }
        );

    } catch (error) {

        console.warn(
            "ASEM location backend:",
            error
        );

    }

}


/* ========================================================
   COPY
======================================================== */

async function copyText(
    value,
    button = null
) {

    if (!value) {
        return false;
    }

    try {

        if (
            navigator.clipboard &&
            window.isSecureContext
        ) {

            await navigator.clipboard.writeText(
                value
            );

        } else {

            const area =
                document.createElement(
                    "textarea"
                );

            area.value =
                value;

            area.style.position =
                "fixed";

            area.style.opacity =
                "0";

            document.body.appendChild(
                area
            );

            area.focus();

            area.select();

            document.execCommand(
                "copy"
            );

            area.remove();

        }

        if (button) {

            const original =
                button.textContent;

            button.textContent =
                translateText(
                    "Copied ✓"
                );

            setTimeout(
                () => {

                    button.textContent =
                        original;

                },
                1500
            );

        }

        return true;

    } catch (error) {

        console.error(
            "ASEM copy:",
            error
        );

        window.prompt(
            "Copy this text:",
            value
        );

        return false;

    }

}


/* ========================================================
   PAYMENT
======================================================== */

function paymentConfiguration() {

    const payment =
        CONFIG_SAFE.payment ||
        CONFIG_SAFE.payments ||
        {};

    return (
        payment &&
        typeof payment === "object"
    )
        ? payment
        : {};

}


function openPayment(
    provider
) {

    const payment =
        paymentConfiguration();

    const key =
        String(provider || "")
            .toLowerCase();

    const url =
        payment[key] ||
        payment[
            `${key}Url`
        ] ||
        "";

    if (!url) {

        console.warn(
            `ASEM: ${provider} payment gateway is not configured.`
        );

        showPaymentMessage(
            provider
        );

        return false;

    }

    return openExternalPage(
        url
    );

}


function showPaymentMessage(
    provider
) {

    let existing =
        byId(
            "asem-payment-message"
        );

    if (!existing) {

        existing =
            document.createElement(
                "div"
            );

        existing.id =
            "asem-payment-message";

        existing.className =
            "asem-payment-message";

        document.body.appendChild(
            existing
        );

    }

    existing.textContent =
        `${provider} payment is not configured in config.js yet.`;

    existing.hidden =
        false;

    setTimeout(
        () => {

            existing.hidden =
                true;

        },
        4000
    );

}


/* ========================================================
   ACTIONS
======================================================== */

function handleSection(
    section,
    loader
) {

    openPageSection(
        section
    );

    if (
        typeof loader ===
        "function"
    ) {

        return loader();

    }

}


const actions = {

    tourism:
        () =>
            handleSection(
                ASEM.sections.tourism,
                loadTourism
            ),

    businesses:
        () =>
            handleSection(
                ASEM.sections.businesses,
                loadBusinesses
            ),

    products:
        () =>
            handleSection(
                ASEM.sections.products,
                loadProducts
            ),

    projects:
        () =>
            handleSection(
                ASEM.sections.projects,
                loadProjects
            ),

    portfolio:
        openPortfolio,

    services:
        openServices,

    contact:
        openContact,

    about:
        openAbout,

    search:
        openGlobalSearch,

    top:
        () =>
            window.scrollTo(
                {
                    top: 0,
                    behavior: "smooth"
                }
            ),

    gps:
        requestGPS,

    payment:
        () =>
            openPayment(
                "default"
            ),

    visa:
        () =>
            openPayment(
                "visa"
            ),

    mastercard:
        () =>
            openPayment(
                "mastercard"
            ),

    paypal:
        () =>
            openPayment(
                "paypal"
            ),

    googlepay:
        () =>
            openPayment(
                "googlepay"
            ),

    applepay:
        () =>
            openPayment(
                "applepay"
            )

};


/* ========================================================
   ACTION ROUTER
======================================================== */

function initializeActionRouter() {

    document.addEventListener(
        "click",
        event => {

            const element =
                event.target.closest(
                    "[data-platform-action]"
                );

            if (!element) {
                return;
            }

            const action =
                element.getAttribute(
                    "data-platform-action"
                );

            const handler =
                actions[action];

            if (
                typeof handler !==
                "function"
            ) {

                console.warn(
                    "ASEM unknown action:",
                    action
                );

                return;

            }

            event.preventDefault();
            event.stopPropagation();

            try {

                const result =
                    handler();

                if (
                    result &&
                    typeof result.then ===
                    "function"
                ) {

                    result.catch(
                        error =>
                            console.error(
                                "ASEM async action:",
                                action,
                                error
                            )
                    );

                }

            } catch (error) {

                console.error(
                    "ASEM action failed:",
                    action,
                    error
                );

            }

        }
    );

}


/* ========================================================
   CARD OPEN / COPY / RETRY
======================================================== */

function initializeDynamicActions() {

    document.addEventListener(
        "click",
        event => {

            const copyButton =
                event.target.closest(
                    "[data-copy]"
                );

            if (copyButton) {

                event.preventDefault();

                copyText(
                    copyButton.dataset.copy ||
                    "",
                    copyButton
                );

                return;

            }

            const openButton =
                event.target.closest(
                    "[data-open-url]"
                );

            if (openButton) {

                event.preventDefault();

                const url =
                    safeURL(
                        openButton.dataset.openUrl
                    );

                if (url) {

                    window.open(
                        url,
                        "_blank",
                        "noopener,noreferrer"
                    );

                }

                return;

            }

            const retry =
                event.target.closest(
                    "[data-retry-grid]"
                );

            if (retry) {

                event.preventDefault();

                const id =
                    retry.dataset.retryGrid;

                if (
                    id ===
                    "tourismGrid"
                ) {

                    loadTourism();

                } else if (
                    id ===
                    "businessesGrid"
                ) {

                    loadBusinesses();

                } else if (
                    id ===
                    "productsGrid"
                ) {

                    loadProducts();

                } else if (
                    id ===
                    "projectsGrid"
                ) {

                    loadProjects();

                }

            }

        }
    );

}


/* ========================================================
   ANCHOR NAVIGATION
======================================================== */

function initializeNavigation() {

    document.addEventListener(
        "click",
        event => {

            const link =
                event.target.closest(
                    'a[href^="#"]'
                );

            if (!link) {
                return;
            }

            const href =
                link.getAttribute(
                    "href"
                );

            if (
                !href ||
                href === "#"
            ) {
                return;
            }

            const id =
                href.substring(1);

            const section =
                byId(id);

            if (!section) {
                return;
            }

            event.preventDefault();

            openPageSection(
                id
            );

        }
    );

}


/* ========================================================
   SEARCH INPUT
======================================================== */

function initializeSearch() {

    const input =
        $(ASEM.selectors.search);

    if (!input) {
        return;
    }

    input.addEventListener(
        "input",
        event => {

            search(
                event.target.value
            );

        }
    );

    input.addEventListener(
        "keydown",
        event => {

            if (
                event.key ===
                "Escape"
            ) {

                input.value =
                    "";

                search(
                    ""
                );

                input.blur();

            }

            if (
                event.key ===
                "Enter"
            ) {

                openGlobalSearch();

                const global =
                    byId(
                        "asem-global-search"
                    );
